# Generated by Django 4.2 on 2024-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['country'], 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='tax',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
